base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.home_page, name="homepage"),
]

jobPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")),
    path("jobs/", include("jobs.urls")),
]

jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("all-categories", views.jobs_by_category, name="jobs_by_category"), #for jobs by category
    path('', views.all_jobs, name='all_jobs'),
]

base/models.py
from django.db import models

# Create your models here.

jobs/models.py
from django.db import models
from datetime import date, timedelta


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.name} - {self.description}"


class Job(models.Model):
    JOB_TYPES = (
        ("FT", "Full-Time"),
        ("PT", "Part-Time"),
        ("IN", "Internship"),
        ("RE", "Remote"),
    )

    title = models.CharField(max_length=200)
    company = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    job_type = models.CharField(max_length=2, choices=JOB_TYPES, default="FT")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="jobs", null=True, blank=True) # link
    salary = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField()
    logo = models.ImageField(upload_to="jobs/logos/", blank=True, null=True)
    featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    application_deadline = models.DateField(default=date.today() + timedelta(days=30))

    def day_left(self):
        delta = self.application_deadline - date.today()
        return max(delta.days, 0)

    def __str__(self):
        return f"{self.title} ({self.company})"

users/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render
from jobs.views import featured_jobs
from jobs.models import Category

# Create your views here.
def home_page(request):
    # logos for infinite loop
    logos = [
        'base/images/logo-visa.svg',
        'base/images/logo-toyota.svg',
        'base/images/logo-google.svg',
        'base/images/logo-paypal.svg',
        'base/images/logo-netflix.svg',
        'base/images/logo-adidas.svg',
        'base/images/logo-abbott.svg',
        'base/images/logo-fedex.svg',
    ]

    # top categories for jobs
    # top_categories = [
    #     {
    #         "name" : "Web Development",
    #         "image" : "base/images/category-development.webp",
    #         "jobs_available" : 17
    #     },
    #     {
    #         "name" : "UX/UI Design",
    #         "image" : "base/images/category-ux_ui.webp",
    #         "jobs_available" : 8
    #     },
    #     {
    #         "name" : "Data Science",
    #         "image" : "base/images/category-data-science.webp",
    #         "jobs_available" : 9
    #     },
    #     {
    #         "name" : "Smart AI Services",
    #         "image" : "base/images/category-AI.webp",
    #         "jobs_available" : 7
    #     },
    #     {
    #         "name" : "Digital Marketing",
    #         "image" : "base/images/category-digital marketing.webp",
    #         "jobs_available" : 12
    #     },
    #     {
    #         "name" : "Mobile App Development",
    #         "image" : "base/images/category-mobile-app.webp",
    #         "jobs_available" : 8
    #     }
    # ]


    # fetch categories dynamically
    top_categories = Category.objects.all()
    for cat in top_categories:
        cat.jobs_available = cat.jobs.count()

    # featued jobs
    featured = featured_jobs(request)

    context = {
        "logos" : logos,
        "top_categories" : top_categories,
        "featured_jobs" : featured
    }

    return render(request, "base/index.html", context)

jobs/views.py
from django.shortcuts import render
from .models import Job, Category

# Create your views here.
def jobs_by_category(request):
    return render(request, "jobs/jobs_by_category.html")

def featured_jobs(request):
    featured_jobs = Job.objects.filter(featured=True).order_by("created_at")[:12]
    return featured_jobs

def all_jobs(request):
    jobs = Job.objects.all().order_by("_created_at")
    return render(request, "jobs/all_jobs.html", {"jobs" : jobs})

users/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en-US">
  <head>
    <!-- meta tags -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta http-equiv="X-UA-Compatible" content="IE=7" />
    <meta name="author" content="Athika Chowdhury Priya" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="keywords"
      content="html, css, bootstrap, javascript, python, django, dbsqlite"
    />
    <!-- favicon -->
    <link
      rel="shortcut icon"
      href="{% static 'base/images/talentgo.webp' %}"
      type="image/x-icon"
    />
    <!-- title tag -->
    <title>TalentGo | Connect. Apply. Succeed.</title>
    <!-- google fonts cdn -->
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Original+Surfer&display=swap"
      rel="stylesheet"
    />
    <!-- font awesome cdn -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- bootstrap css cdn -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
    />
    <!-- css -->
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}" />
    <!-- responsive css -->
    <link rel="stylesheet" href="{% static 'base/css/responsive.css' %}" />
  </head>
  <body>
    <!-- header starts here -->
    <header>
      <!-- nav starts -->
      <nav class="navbar navbar-expand-lg py-3 fixed-top">
        <div class="container align-items-center">
          <!-- navbar logo -->
          <a
            href="{% url 'homepage' %}"
            class="nav-logo__container text-decoration-none d-flex align-items-center"
          >
            <img
              src="{% static 'base/images/talentgo.webp' %}"
              alt="Logo"
              class="nav-logo me-1"
            />
            <h1 class="brand-name">TalentGo</h1>
          </a>
          <!-- navbar nav items -->
          <div class="offcanvas offcanvas-end" id="myNav" tabindex="-1">
            <!-- offcanvas header -->
            <div class="offcanvas-header">
              <button
                type="button"
                class="btn-close btn-close-white"
                data-bs-dismiss="offcanvas"
                aria-label="Close"
              ></button>
            </div>
            <!-- navbar nav -->
            <ul
              class="navbar-nav ms-0 mb-lg-0 text-center justify-content-center justify-content-lg-start"
            >
              <li class="nav-item">
                <a
                  href="{% url 'homepage' %}"
                  class="nav-link mx-0 ms-lg-5 me-lg-2 py-lg-1 mb-1 mt-0 mb-lg-0"
                  >Home</a
                >
              </li>
              <li class="nav-item">
                <a
                  href="{% url 'jobs_by_category' %}"
                  class="nav-link mx-0 mx-lg-2 py-lg-1 mb-lg-0"
                  >Categories</a
                >
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link mx-0 mx-lg-2 py-lg-1 mb-lg-0"
                  >Jobs</a
                >
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link mx-0 ms-lg-2 me-0 py-lg-1 mb-0"
                  >Companies</a
                >
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link mx-0 ms-lg-2 me-0 py-lg-1 mb-0"
                  >Candidates</a
                >
              </li>
            </ul>
          </div>
          <!-- nav logins and toggler starts -->
          <div class="d-flex justify-content-end">
            <!-- nav logins -->
            <div class="nav-logins mx-lg-0">
              <ul class="d-flex align-items-center justify-content-end">
                <li class="nav-item">
                  <a href="#" class="nav-link text-decoration-none ms-0 me-2"
                    >Sign In</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    href="#"
                    class="nav-link text-decoration-none ms-2 me-0 register-btn"
                    >Register</a
                  >
                </li>
              </ul>
            </div>
            <!-- offcanvas toggler -->
            <button
              class="navbar-toggler mx-lg-0 ms-3"
              type="button"
              data-bs-toggle="offcanvas"
              data-bs-target="#myNav"
              aria-controls="myNav"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fa-solid fa-bars-staggered"></i>
            </button>
          </div>
          <!-- nav logins and toggler ends -->
        </div>
      </nav>
      <!-- nav ends -->
    </header>
    <!-- header ends here -->

    <!-- main starts here -->
    <main>
        {% block content %}
        <!-- hero starts here -->
        <section id="hero-section">
            <div class="container">
            <div class="hero-contents">
                <h2 class="hero-heading">
                Help your team thrive with <span>freelance</span> experts
                </h2>
                <p class="hero-description mt-2 mt-lg-3">
                Company reviews. Salaries. Interviews. Jobs.
                </p>
                <div class="hero-buttons d-flex mt-4 mt-lg-4">
                <a
                    href="#"
                    class="text-decoration-none my-btn get-started__btn me-4"
                    >Get Started <i class="fa-solid fa-arrow-right-to-bracket"></i>
                </a>
                <a href="#" class="text-decoration-none my-btn learn-more__btn"
                    >Learn More
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                </a>
                </div>
            </div>
            </div>
        </section>
        <!-- hero ends here -->

        <!-- infinite loop starts here -->
        <section id="infinite-loop">
            <div class="container-fluid">
            <div class="logo-slider">
                <div class="logo-overflow d-flex">
                <div class="logo-wrapper d-flex">
                    {% for logo in logos %}
                    <div class="logo-item">
                    <img src="{% static logo %}" alt="Logo" />
                    </div>
                    {% endfor %} {% for logo in logos %}
                    <div class="logo-item">
                    <img src="{% static logo %}" alt="Logo" />
                    </div>
                    {% endfor %}
                </div>
                </div>
            </div>
            </div>
        </section>
        <!-- infinite loop ends here -->

        <!-- top categories starts here -->
        <section id="top-categories" class="section-padding">
            <div class="container">
            <div class="row">
                <h3 class="section-heading">Top categories</h3>
                <p class="section-description"> Easily find the right service from over 2000+ skills</p>
            </div>
            <!-- slider categories starts -->
            <!-- <div class="row mt-3">
                {% for category in top_categories %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 category-box text-center">
                <img
                    src="{% static category.image %}"
                    alt="{{ category.name }}"
                    class="img-fluid"
                />
                
                <div class="overlay">
                    <a class="category-name">{{ category.name }}</a>
                    <p class="jobs-available">
                    {{ category.jobs_available }} Jobs Available
                    </p>
                </div>
                </div>
                {% endfor %}
            </div> -->


            <div class="row mt-3 text-center ">
              {% for category in top_categories %}
              <div class="col-12 col-sm-6 col-md-4 col-lg-3 ">
                <div class="top-category__items">
                  <div class="leaf-icon mb-4">
                    <i class="fa-solid fa-leaf"></i>
                  </div>
                  <h4 class="category-name">{{ category.name }}</h4>
                  <p class="category-description mt-2 ">{{ category.description }}</p>
                  <a href="#" class="view-more__btn">View More</a>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- slider categories ends -->
            </div>
        </section>
        <!-- top categories ends here -->


        <!-- featured jobs starts here -->
        <section id="featured-jobs" class="section-padding">
            <div class="container">
                <div class="row">
                    <h3 class="section-heading">Featured jobs</h3>
                    <p class="section-description">2020 jobs live – 293 added today.</p>
                </div>
                <!-- featured jobs sliders starts -->
                <div class="row mt-3">
                    
                  <div class="job-slider" id="job-slider">
                  {% for job in featured_jobs %}
                    <div class="job-card">
                      {% if job.logo %}
                        <img src="{{ job.logo.url }}" alt="{{ job.company }} logo">
                      {% endif %}
                      <div class="job-info">
                        <h3>{{ job.title }}</h3>
                        <p>{{ job.company }} — {{ job.location }}</p>
                        <p>Category: {{ job.category.name }}</p>
                        <p>Type: {{ job.get_job_type_display }}</p>
                        <p class="deadline">
                          {% if job.days_left %}
                            {{ job.days_left }} days left to apply
                          {% else %}
                            Closed
                          {% endif %}
                        </p>
                      </div>
                    </div>
                  {% empty %}
                    <p>No featured jobs available.</p>
                  {% endfor %}
                </div>

                <a href="{% url 'all_jobs' %}" class="view-all-btn">View All Jobs</a>

                </div>
                <!-- featured jobs sliders ends -->
            </div>
        </section>
        <!-- featured jobs ends here -->


    </main>
    {% endblock %}
    <!-- main ends here -->

    <!-- footer starts here -->
    <footer></footer>
    <!-- footer ends here -->

    <!-- jquery cdn -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- bootstrap js cdn -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <!-- my js -->
    <script src="{% static 'base/js/top_categories_slider.js' %}"></script>
  </body>
</html>

jobs/templates/jobs/jobs_by_category.html
<h1>This is jobs by category page</h1>

<!-- wanna use this page all jobs also including filtering later -->